### ISSUE TITLE
README.md backtick (maybe on purpose?)

### ISSUE THREAD

**Issue by faeb187** [Jac-Zac/Nibbler_MacOS#2]
Hi

first thank you for your work, is it quite recent or why do you have only 2 stars?
I've just figured that the old variation of starting lc0 in nibbler wasn't working anymore, so I'm trying yours...

**In your readme file you put a `backtick at the end of the comand**, that might be irritating for less experienced users, was it on purpose to avoid accidental return of the command? otherwise you might remove it =)

still installing, getting excited.
best regards from Switzerland (lichess: faeb187)

**Comment by Jac-Zac** [comment]
Hi, thanks am happy you like it. Also hopefully it will get some more stars in the future. In conclusion thanks for making me notice the mistake in the README file because I totally would have overlooked it
