### ISSUE TITLE
Lc0 in x86x64 binary not working 

### ISSUE THREAD

**Issue by tillchess** [Jac-Zac/Nibbler_MacOS#4]
I get "illegal hardware instruction  ./lc0" when I start lc0 in the x86_64 binary 2.1.7
 release.

Fix:
I compiled a working  Lc0 v0.28 for regular 64 bit Intel Mac's which you can get here

http://www.solidfiles.com/v/YLXZDQDZynq7Z

**Comment by Jac-Zac** [comment]
I'm not really sure why because It works on a x86_64 mac I tried it for

**Comment by Jac-Zac** [comment]
I'll also try to make a new release for x86 mac in the future btw

**Comment by tillchess** [comment]
It depends what you kind of instruction set you have used for the Lc0 x86_64  compile . 

I think the Lc0 build scripts builds the binary for your system you have .

**Comment by Jac-Zac** [comment]
No I now but I mean I have an m1 macbook and I used that to run the one that I made for apple silicon. For the other one which is bundled for x86 I have used an old mac mini and it works for me

**Comment by tillchess** [comment]
I have build Lc0 on a 2012 Mac mini with  Intel Core i5. 

You binary shows "illegal hardware instruction" .

**Comment by Jac-Zac** [comment]
Interesting because It does work on my mac mini but I agree that if I run it on my m1 macbook through rosetta. So If I emulate the x86_64 architecture it actually doesn't work but I have not other mac to test it on. Anyway I said I'll try to make a new version you'll tell me if that works maybe

**Comment by Jac-Zac** [comment]
Ok I made a new version that you can find inside the repo now. So you can clone it and try it it should be working, it also worked for me and both mac mini and also running it trough rosetta on my m1 macbook. Also I have made changed the neural net weight to new ones which should make the engine slightly better

**Comment by Jac-Zac** [comment]
Ok I made a new version that you can find inside the repo now. So you can clone it and try it it should be working, it also worked for me and both mac mini and also running it trough rosetta on my m1 macbook. Also I have made changed the neural net weight to new ones which should make the engine slightly better

**Comment by tillchess** [comment]
lc0 in your new binary works. Nice!

**Comment by Jac-Zac** [comment]
Perfect I'm happy it works. Furthermore now the version of both the app and the engines are new. Anyway thanks for telling me about the issue and also providing an alternative solution, really appreciated
