### ISSUE TITLE
Cannot run Nibbler on Monterey 12.6 saying that application is damaged and cannot be opened

### ISSUE THREAD

**Issue by tomaz2k** [Jac-Zac/Nibbler_MacOS#7]
I have this error with the latest version and the previous one, thanks for your help, I really appreciate.

**Comment by xdemiansmithx** [comment]
try `xattr -d com.apple.quarantine /Applications/Nibbler` in Terminal

**Comment by tomaz2k** [comment]
thanks a lot ! this is now working !
Great work I really appreciate.
