### ISSUE TITLE
Nibbler - display

### ISSUE THREAD

**Issue by verutak** [Jac-Zac/Nibbler_MacOS#8]
I´m a naive user of Nibbler. It worked fine for me, but suddenly it is not showing any display. No chessbord, not showing known enginines etc. Can anybody send me a hint how to deal with this? Thanks.

**Comment by Jac-Zac** [comment]
Try updating to the latest release and if you have some problem tell me more specifically which is your setup. I hope It can help

**Comment by verutak** [comment]
Thank you. Update helped.

út 29. 11. 2022 v 22:22 odesílatel Jacopo Zacchigna <
***@***.***> napsal:

**Comment by Jac-Zac** [comment]
perfect
